language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo c
  - hexo g

after_script:
  - hexo d
  - cd ./public
  - git init
  - git config user.name "xhc6"
  - git config user.email "xhangchen@126.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/hangchenX/hangchenX.github.io.git